small syntax changes
ivana-mag/vue-skeleton pull request #1
Opened 2021-04-03 10:02 UTC by ivana-mag

2021-04-05 05:55 UTC, SchnapsterDog requested changes
Форматирај кодот, овие две измени направи ги во scss и ќе мерџниме на мастер.

2021-04-05 05:55 UTC, SchnapsterDog commented on vue-skeleton/src/assets/scss/parts/_footer.scss
> +.footer a {
Ова можеш да го ставиш исто во footer класата пошто за него се однесува. Scss ни дозволува таква синтакса.

2021-04-05 05:55 UTC, SchnapsterDog commented on vue-skeleton/src/assets/scss/parts/_header.scss
> +.header a {
Исто и ова header a може да го ставиш во .header класата внатре. Само a  { // } ќе го пишеше внатре.

2021-04-05 19:53 UTC, ivana-mag commented on vue-skeleton/src/assets/scss/parts/_footer.scss
> +.footer a {
Не нзнаев дека може и вака, супер, ги сменав.

2021-04-05 19:54 UTC, ivana-mag commented on vue-skeleton/src/assets/scss/parts/_header.scss
> +.header a {
Сменето.

2021-04-06 21:29 UTC, SchnapsterDog approved these changes

2021-04-06 21:29 UTC, merged